### ISSUE TITLE
todo to express

### ISSUE THREAD

**Issue by chyroc** [Chyroc/gor#5]
- [ ] app
  - [ ] fields
    - [ ] app.locals
    - [ ] app.mountpath
  - [ ] methods
    - [x] app.all()
    - [x] app.delete()
    - [ ] app.disable()
    - [ ] app.disabled()
    - [ ] app.enable()
    - [ ] app.enabled()
    - [ ] app.engine()
    - [x] app.get()
    - [x] app.get()
    - [x] app.listen()
    - [x] app.METHOD()
    - [ ] app.param()
    - [ ] app.path()
    - [x] app.post()
    - [x] app.put()
    - [x] app.render()
    - [ ] app.route()
    - [ ] app.set()
    - [x] app.use()
- [ ] Request
  - [ ] fields
    - [ ] req.app
    - [x] req.baseUrl
    - [x] req.body
    - [ ] req.cookies
    - [ ] req.fresh
    - [x] req.hostname
    - [ ] req.ip
    - [ ] req.ips
    - [x] req.method
    - [x] req.originalUrl
    - [x] req.params
    - [ ] req.path
    - [x] req.protocol
    - [x] req.query
    - [ ] req.route
    - [x] req.secure
    - [ ] req.signedCookies
    - [ ] req.stale
    - [ ] req.subdomains
    - [ ] req.xhr
  - [ ] methods
    - [ ] req.accepts()
    - [ ] req.acceptsCharsets()
    - [ ] req.acceptsEncodings()
    - [ ] req.acceptsLanguages()
    - [ ] req.get()
    - [ ] req.is()
    - [ ] req.param()
    - [ ] req.range()
- [ ] Response methods
  - [ ] fields
    - [ ] res.app
    - [ ] res.headersSent
    - [ ] res.locals
  - [ ] methods
    - [x] res.append()
    - [ ] res.attachment()
    - [ ] res.cookie()
    - [ ] res.clearCookie()
    - [ ] res.download()
    - [x] res.end()
    - [ ] res.format()
    - [ ] res.get()
    - [x] res.json()
    - [ ] res.jsonp()
    - [ ] res.links()
    - [ ] res.location()
    - [x] res.redirect()
    - [ ] res.render()
    - [x] res.send()
    - [ ] res.sendFile()
    - [x] res.sendStatus()
    - [ ] res.set()
    - [x] res.status()
    - [ ] res.type()
    - [ ] res.vary()
- [ ] router
  - [ ] route paths based on string patterns
  - [ ] route paths based on regular expressions
  - [ ] Route parameters
  - [ ] Route handlers
  - [ ] app.route()
  - [ ] express.Router
  - [x] app.use()
  - [ ] [app.all('/secret', function (req, res, next)](http://expressjs.com/en/guide/routing.html)
- [ ] middleware
- [ ] template engines
- [ ] Error handling
- [ ] Debugging
